site_name: Battery Safety Controller
repo_url: https://github.com/shining-man/bsc_fw
edit_uri: https://github.com/bsc-org/bsc/edit/main/docs

theme:
  name: material
  logo: img/favicon.png
  favicon: img/favicon.png
  language: de
  highlightjs: true

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Zu dunklem Modus wechseln
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Zu hellem Modus wechseln

  features:
    - content.action.edit
    - navigation.indexes
    - navigation.sections

  icon:
    repo: fontawesome/brands/github

hooks:
  - hooks/bsc_settings.py

watch:
  - bsc_settings

plugins:
  - blog:
      blog_toc: true
      post_url_format: "{file}"
  - search

  - git-revision-date-localized:
      enable_creation_date: false

extra_css:
  - css/extra.css

extra_javascript:
  - js/external-links.js
  - js/theme-sync.js
  - js/bsc-settings.js

#extra:
#  alternate:
#    - name: Deutsch
#      link: /
#      lang: de
#    - name: English
#      link: /en/ 
#      lang: en

markdown_extensions:
  - attr_list  
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format      
      
nav:
  - User Guide:
    - Systemübersicht: system_overview.md
    - Versionsvergleich /<br>Version Comparison: comparison_sw.md
    - Erste Schritte:
      - Erste Informationen: first_steps.md
      - Programmieren des BSC: first_steps_programming.md
      - Hardware anschließen: first_steps_hardware.md
      - Einstellungen im BSC: first_steps_settings.md
    - Hardware: hardware.md
    - Unterstüzte Geräte:
      - BMS: devices/bms.md
      - Wechselrichter: devices/wechselrichter.md
      - Externe Shunts: devices/externer_shunt.md
      - Weitere Geräte: devices/weitere_geraete.md
    - Konfiguration:
      - Allgemeines & Dashboard: dashboard.md
      - System: settings_bsc.md
      - Trigger: settings_bsc_trigger.md
      - Schnittstellen: settings_bsc_interfaces.md
      - Devices:
        - Data-Devices: settings_bsc_data_devices.md
        - Group Devices: settings_bsc_group-devices.md
        - Wartung: settings_maintenance.md
      - Wechselrichter & Laderegelung: 
        - Allgemein: settings_inverter.md
        - Laden: settings_inverter_charge.md
        - Entladen: settings_inverter_discharge.md
      - Alarmregeln: settings_bsc_alarmrules.md
      - Das Log des BSC: log.md
      - Einrichtungsassistenten: setup_assistant.md
      - Beispielkonfigurationen: beispiel_konfigurationen.md
    - Integration (MQTT, REST):
      - MQTT: mqtt.md
      - REST-API: restapi.md
    - Fernwartung (T-Connect): settings_servicelink.md
    - Troubleshooting: troubleshooting.md 
    - Sonstiges: 
      - Test ohne BSC Hardware: BSC_ohne_orig_hardware.md
      - Bestückung Varianten: bestückung_varianten.md

  - Ressourcen:
    - Donate: supporter.md
    - Demo (Supporter-Version): demo/app.html
    - Issues:
      - Issues: https://github.com/shining-man/bsc_fw/issues
      - Issues (Nur für Supporter): https://github.com/bsc-org/bsc_fw_insider/issues
    - Blog:
      - blog/index.md
    - About:
      - Release Notes: https://github.com/shining-man/bsc_fw/releases